### ISSUE TITLE
GPU Memory torch.cuda.OutOfMemoryError

### ISSUE THREAD

**Issue by frixos25** [Rikorose/DeepFilterNet#553]
Hello,

when i try to filter a file longer than some minutes this error appears:
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.36 GiB. GPU
I have 4GB GPU memory.

Is there a parameter to reduce the memory usage?

**Comment by frixos25** [comment]
Nobody an idea?

**Comment by krane5555** [comment]
Segment the audio in smaller chunks and then process, i had the same issue and it worked.
